# Generated by Django 4.2.16 on 2024-09-17 09:24

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ehr_id', models.CharField(blank=True, max_length=50)),
                ('version_id', models.CharField(blank=True, max_length=60)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, max_length=50)),
                ('uid', base.models.PatientAutoField(blank=True, max_length=50, prefix='PAT-', unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
