# Generated by Django 4.2.16 on 2024-09-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
