# Generated by Django 4.2.16 on 2024-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_patient_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='uid',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
