# Generated by Django 4.2.16 on 2024-09-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_patient_uid_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='uid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
