# Generated by Django 4.2.16 on 2024-09-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_patient_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='uid',
        ),
    ]
